project:
  type: website
  output-dir: _site

website:
  title: "AI Scratchpad"
  site-url: https://aiscratchpad.com
  description: "A technical blog with practical guides for AI and Machine Learning with code in Python and R, a hands-on approach to data science."

  navbar:
    right:
      - privacy.qmd
      - about.qmd
      - icon: github
        href: https://github.com/januarytabaka
      - icon: twitter
        href: https://x.com/january_tabaka
      - text: EN
        menu:
          - text: ES
            href: https://es.aiscratchpad.com
          - text: CA
            href: https://ca.aiscratchpad.com
      - icon: rss
        href: index.xml
  comments:
    giscus:
      repo: januarytabaka/januarytabaka.github.io
      repo-id: "R_kgDOPTiMRA"
      category: "General"
      category-id: "DIC_kwDOPTiMRM4CtgfQ"
      mapping: "pathname"
      reactions-enabled: true
      theme: "preferred_color_scheme"
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header: _includes/matomo.html
    security:
      content-security-policy:
        # Allows scripts from your own site and giscus
        script-src:
          - "'self'"
          - "https://giscus.app"
      referrer-policy: "no-referrer"

engine: knitr
knitr:
  opts_chunk: 
    engine.path:
      python: /usr/bin/python3
